# Generated by Django 2.0.1 on 2018-07-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=60, verbose_name='street')),
                ('number', models.CharField(blank=True, max_length=10, verbose_name='number')),
                ('zip_code', models.CharField(blank=True, max_length=60, verbose_name='zip_code')),
                ('latitude', models.DecimalField(decimal_places=18, max_digits=20, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=18, max_digits=20, verbose_name='longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60, verbose_name='description')),
                ('square_meter', models.PositiveSmallIntegerField(verbose_name='square_meter')),
                ('number_of_bedrooms', models.PositiveSmallIntegerField(verbose_name='number_of_bedrooms')),
                ('number_of_bathrooms', models.PositiveSmallIntegerField(verbose_name='number_of_bathrooms')),
                ('image', models.ImageField(upload_to='images/property', verbose_name='image')),
                ('address', models.ForeignKey(blank=True, on_delete=True, to='imovel.Address')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'properties',
                'ordering': ['description', 'square_meter', 'number_of_bathrooms'],
            },
        ),
    ]
