# Generated by Django 2.0.1 on 2018-07-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=60, verbose_name='street')),
                ('number', models.CharField(blank=True, max_length=10, verbose_name='number')),
                ('zip_code', models.CharField(blank=True, max_length=60, verbose_name='zip_code')),
                ('latitude', models.BigIntegerField(verbose_name='latitude')),
                ('longitude', models.BigIntegerField(verbose_name='longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('square_meter', models.IntegerField(verbose_name='square_meter')),
                ('number_of_bedrooms', models.PositiveSmallIntegerField(blank=True, verbose_name='number_of_bedrooms')),
                ('number_of_bathrooms', models.PositiveSmallIntegerField(blank=True, verbose_name='number_of_bathrooms')),
                ('address', models.ForeignKey(on_delete=False, to='imovel.Address')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['name', 'square_meter', 'number_of_bathrooms'],
                'verbose_name': 'Property',
            },
        ),
    ]
