# Generated by Django 2.0.1 on 2018-07-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('contact_phone', models.CharField(max_length=12, verbose_name='contact_phone')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='contact_email')),
                ('imovel', models.ForeignKey(on_delete=False, to='imovel.Property')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['description', 'price'],
            },
        ),
    ]
